name: Python Selenium CI

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

# Gives the workflow permissions to create gh-pages branch and deploy to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  actions: write
  deployments: write

# Environment for GitHub Pages
env:
  PYTHON_VERSION: "3.11"

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | cut -d ' ' -f 3 | cut -d '.' -f 1)
          wget -q "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.109/linux64/chromedriver-linux64.zip"
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting
        run: |
          flake8 .
          ruff check .
          pylint $(git ls-files '*.py')

      - name: Run tests with pytest and generate Allure report
        run: |
          pytest --alluredir=./allure-results

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: allure-results
          path: allure-results
          retention-days: 30

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_report: allure-report

      - name: Configure Pages
        if: always()
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

      - name: Deploy to GitHub Pages
        if: always()
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Merge to main if tests pass
        if: success() && github.ref == 'refs/heads/test'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git fetch origin main:main
          git checkout main
          git merge --no-ff ${{ github.sha }} -m "Auto-merge test branch to main"
          git push origin main
