name: Python Selenium CI

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

permissions:
  contents: write
  pages: write
  id-token: write
  actions: write
  deployments: write

env:
  PYTHON_VERSION: "3.11"

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1)
          CHROMEDRIVER_URL=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_${CHROME_VERSION}" | grep -oP 'https://[^"]+linux64/chromedriver-linux64.zip')
          wget -q "$CHROMEDRIVER_URL"
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting
        run: |
          flake8 .
          ruff check .
          pylint $(git ls-files '*.py')

      - name: Run tests with pytest and generate Allure report
        run: |
          pytest --alluredir=./allure-results

      - name: Debug: Check allure-results directory
        if: always()
        run: |
          ls -al ./allure-results || echo "allure-results directory not found"

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 30

      - name: Install Allure CLI
        run: |
          wget -q https://github.com/allure-framework/allurectl/releases/download/2.29.0/allurectl_linux_amd64 -O allurectl
          chmod +x allurectl
          sudo mv allurectl /usr/local/bin/

      - name: Generate Allure report
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_report: allure-report

      - name: Debug: Check allure-report directory
        if: always()
        run: |
          ls -al ./allure-report || echo "allure-report directory not found"

      - name: Debug: Check temp directory
        if: always()
        run: |
          ls -al /home/runner/work/_temp/ || echo "Temp directory not accessible"

      - name: Upload Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

      - name: Deploy to GitHub Pages
        if: always()
        id: deployment
        uses: actions/deploy-pages@v4